const data = {
  products: [
    {
      name: 'Monstera',
      slug: 'monstera',
      category: 'Suculentas',
      image: '/images/monstera.jpg',
      price: 70,
      brand: 'Ajal de Raiz',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Suculenta Monstera en musgo n° 10',
      isFeatured: true,
      banner: '/images/banner1.jpg,',
    },
    {
      name: 'kokedama potus',
      slug: 'kokedama-potus',
      category: 'Kokedamas',
      image: '/images/kokedama-potus.jpg',
      price: 100,
      brand: 'Ajal de Raiz',
      rating: 4.9,
      numReviews: 5,
      countInStock: 10,
      description: 'Un lindo kokedama hecho con musgo barba de viejo y planta potus verde',
      isFeatured: true,
      banner: '/images/banner1.jpg,',
    },
    {
      name: 'Trebol oxalis',
      slug: 'trebol-oxalis',
      category: 'Plantas',
      image: '/images/trebol-oxaris.jpg',
      price: 150,
      brand: 'Ajal de Raiz',
      rating: 4.8,
      numReviews: 16,
      countInStock: 2,
      description: 'Trebol oxalis importado',
      isFeatured: false,
    },
    {
      name: 'Sansiveira',
      slug: 'sansiveira',
      category: 'Plantas',
      image: '/images/sansiveira.jpg',
      price: 40,
      brand: 'Ajal de Raiz',
      rating: 4.0,
      numReviews: 30,
      countInStock: 50,
      description: 'La mejor planta que puedes tener en el interior.',
      isFeatured: true,
    },
    {
      name: 'Cactus y suculentas',
      slug: 'cactus-y-suculentas',
      category: 'Control de Plagas',
      image: '/images/cactus-Ecomambo-30.jpg',
      price: 99,
      brand: 'Ecomambo',
      rating: 5.0,
      numReviews: 11,
      countInStock: 5,
      description:
        'Control de plagas para cactus y suculentas de la mejor marca ecomambo, productos orgánicos.',
      isFeatured: false,
    },
  ],
}

export default data
